#################################################################
# Example render.yaml                                           #
# Do not use this file directly! Consult it for reference only. #
#################################################################

previews:
  generation: automatic # Enable preview environments

# List all services 
services:
  - type: web
    name: api  # Nom du service, correspond au dossier
    runtime: python
    region: oregon  # ou frankfurt, singapore...
    plan: free  # ou starter/pro si nécessaire
    buildCommand: |
      pip install -r requirements.txt
    startCommand: |
      uvicorn api.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PORT
        value: 8000
      - key: ENV
        value: production

